galaxy_info:
  role_name: HA-Proxy
  author: Allan Taylor
  description: Configures a pair of HA Proxy load balancers for highly available K8S control plane.
  company: ANET
  license: GPLv3
  min_ansible_version: 2.4