galaxy_info:
  role_name: Kubernetes-Control-Plane-Master
  author: Allan Taylor
  description: A playbook to deploy the first Kuberentes control plane server.
  company: ANET
  license: GPLv3
  min_ansible_version: 2.4