---
- hosts: ha-proxy-master
  gather_facts: True
  become: True
  roles:
    - role: common
      vars:
        selinux_state: disabled

    - role: HA-Proxy
      vars:
        haproxy_max_connections: 500
        k8s_control_plane_1_hostname: k8s-master-1.anet.internal
        k8s_control_plane_1_ip: 192.168.4.10
        k8s_control_plane_2_hostname: k8s-master-2.anet.internal
        k8s_control_plane_2_ip: 192.168.4.11
        k8s_control_plane_3_hostname: k8s-master-3.anet.internal
        k8s_control_plane_3_ip: 192.168.4.12
        ethernet_interface: ens33
        keepalive_state: MASTER
        keepalive_priority: 101
        keepalive_vip: 192.168.4.13
        keepalive_interval: 1


- hosts: ha-proxy-backup
  gather_facts: True
  become: True
  roles:
    - role: common
      vars:
        selinux_state: disabled

    - role: HA-Proxy
      vars:
        haproxy_max_connections: 500
        k8s_control_plane_1_hostname: k8s-master-1.anet.internal
        k8s_control_plane_1_ip: 192.168.4.10
        k8s_control_plane_2_hostname: k8s-master-2.anet.internal
        k8s_control_plane_2_ip: 192.168.4.11
        k8s_control_plane_3_hostname: k8s-master-3.anet.internal
        k8s_control_plane_3_ip: 192.168.4.12
        ethernet_interface: ens33
        keepalive_state: BACKUP
        keepalive_priority: 100
        keepalive_vip: 192.168.4.13
        keepalive_interval: 1


- hosts: control-plane
  gather_facts: True
  become: True
  roles:
    - role: common
      vars:
        selinux_state: disabled

    - role: Docker
      vars:
        user_added_to_docker_group: ansible

    - role: Kubernetes-Control-Plane
      vars:
        k8s_admin_user: allan
        k8s_init_output_file: /root/k8s-init
        pod_network: 10.244.0.0/16
        network_overlay: https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
        control_plane_vip_dns: k8s-master-vip.anet.internal


- hosts: control-plane-additional
  gather_facts: True
  become: True
  roles:
    - role: common
      vars:
        selinux_state: disabled

    - role: Docker
      vars:
        user_added_to_docker_group: allan

    - role: Kubernetes-Control-Plane-Additional
      vars:
          cluster_api: k8s-master-vip.anet.internal:6443
          token: 456y7y.f06433zsjfid55j7
          discovery_token_ca_cert_hash: sha256:d15265ed549d910c89a60871ed0e0f408cb922c0649e1de8c6be8217d4c5a533
          certificate_key: 641fee9b2132c0662b4b4b16183f8f16173431f41ca8d70bbe924d365ad77d9d