---
- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_factsansible_facts['os_family']

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_factsansible_facts['distribution_major_version']

- hosts: control-plane-master
  gather_facts: True
  become: True
  roles:
    - role: Docker
      vars:
        user_added_to_docker_group: ansible

    - role: Kubernetes-Control-Plane-Master
      vars:
        k8s_admin_user: ansible
        k8s_init_output_file: /root/k8s-init