---
- hosts: control-plane-master
  gather_facts: True
  become: True
  roles:
    - role: common
      vars:
        host_name: k8s-master-1
        fqdn_hostname: k8s-master-1.anet.internal
        selinux_state: disabled
        root_pw: Passw@ord123!

    - role: Docker
      vars:
        user_added_to_docker_group: ansible

    - role: Kubernetes-Control-Plane-Master
      vars:
        k8s_admin_user: ansible
        k8s_init_output_file: /root/k8s-init