- name: Allow BGP
  firewalld:
    port: 179/tcp
    permanent: yes
    state: enabled

- name: Allow Kubelet API
  firewalld:
    port: 10250/tcp
    permanent: yes
    state: enabled

- name: Allow NodePort service
  firewalld:
    port: 30000-32767/tcp
    permanent: yes
    state: enabled
    
- name: Allow DNS
  firewalld:
    service: dns
    permanent: yes
    state: enabled