---
- name: Configure IP forwarding
  shell: |
    modprobe br_netfilter
    firewall-cmd --add-masquerade --permanent
    firewall-cmd --reload
    echo 'net.bridge.bridge-nf-call-ip6tables = 1' > /etc/sysctl.d/k8s.conf
    echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.d/k8s.conf
    sysctl --system

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab

- name: Copy Kubernetes repo file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Kubernetes packages
  dnf:
    name:
      - kubeadm
      - kubelet
      - kubectl
  when:
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: Install Kubernetes packages
  yum:
    name:
      - kubeadm
      - kubelet
      - kubectl
  when:
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "7"

- name: Start and enable kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Join worker to cluster
  shell: |
    kubeadm join {{ api_endpoint }} \
       --token {{ cluster_token }}  \
       --discovery-token-ca-cert-hash {{ discovery_token_ca_cert_hash }}
       
# - name: Reboot the server
#   shell: |
#     reboot
