---
- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_factsansible_facts['os_family']

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_factsansible_facts['distribution_major_version']
    
- name: Include task list in play
  include_tasks: firewalld.yml
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"

- name: Configure IP forwarding
  shell: |
    modprobe br_netfilter
    firewall-cmd --add-masquerade --permanent
    firewall-cmd --reload
    echo 'net.bridge.bridge-nf-call-ip6tables = 1' > /etc/sysctl.d/k8s.conf
    echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.d/k8s.conf
    sysctl --system

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab