---
- include_tasks: centos8.yml
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"


- name: Include task list in play
  include_tasks: firewalld.yml

- name: Configure IP forwarding
  shell: |
    modprobe br_netfilter
    firewall-cmd --add-masquerade --permanent
    firewall-cmd --reload
    echo 'net.bridge.bridge-nf-call-ip6tables = 1' > /etc/sysctl.d/k8s.conf
    echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.d/k8s.conf
    sysctl --system

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab