---
- name: Show OS family
  ansible.builtin.debug:
    var: ansible_facts['os_family']

- name: Show OS distrobution
  ansible.builtin.debug:
    var: ansible_facts['distribution']

- name: Show distribution version
  ansible.builtin.debug:
    var: ansible_facts['distribution_major_version']

- name: Patch OS
  dnf:
    name: "*"
    state: latest
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: Patch OS
  yum:
    name: "*"
    state: latest
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "7"

- name: Install packages
  dnf:
    name:
      - git
      - mlocate
      - vim
      - wget
      - curl
      - setroubleshoot
      - zip
      - unzip
      - yum-utils
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: Install packages
  yum:
    name:
      - git
      - mlocate
      - vim
      - wget
      - curl
      - setroubleshoot
      - zip
      - unzip
      - yum-utils
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "7"

- name: Configure SELinux
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"