---
- name: Show OS family
  ansible.builtin.debug:
    var: ansible_facts['os_family']

- name: Show OS distrobution
  ansible.builtin.debug:
    var: ansible_facts['distribution']

- name: Show distribution version
  ansible.builtin.debug:
    var: ansible_facts['distribution_major_version']

- name: Patch OS
  dnf:
    name: "*"
    state: latest

- name: Install packages
  dnf:
    name:
      - git
      - mlocate
      - vim
      - wget
      - curl
      - setroubleshoot
      - zip
      - unzip

- name: Configure SELinux
  selinux:
    policy: targeted
    state: "{{ selinux_state }}"

