---
- name: Add Docker repo
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  shell: |
    dnf -y install docker-ce docker-ce-cli containerd.io  --nobest
  ignore_errors: yes
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: Install Docker
  shell: |
    yum -y install docker-ce docker-ce-cli containerd.io
  ignore_errors: yes
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "7"

- name: Copy DNF config
  copy:
    src: dnf.conf
    dest: /etc/dnf/dnf.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add the user to the docker groups
  user:
    name: "{{ user_added_to_docker_group }}"
    group: docker
    append: yes